// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

// Flat config; Nuxt generates the base rules, we only override.
export default withNuxt(
  {
    // Vendored shadcn-vue primitives, generated by the CLI and not hand-tuned,
    // so we don't hold them to our own rules (e.g. require-default-prop).
    ignores: ['app/components/ui/**'],
  },
  {
    rules: {
      'vue/html-self-closing': 'off',
      // Ban `any` (syntactic rule, no type-info needed → fast).
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
)
